wifi:
  ssid: !secret iotwifissid
  password: !secret iotwifipass
  fast_connect: on
  domain: .khamu.lan
  power_save_mode: none

  ap:
    ssid: ${devicename}
    password: !secret apFallBackPass

captive_portal:

logger:
  baud_rate: 0

ota:
  safe_mode: True
  password: !secret espotapass
  
web_server:
  port: 80
  auth:
    username: admin
    password: !secret webpass
