version: "3"

services:
  server:
    image: gitea/gitea:1.16.4
    container_name: Gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8080:3000"
      - "8022:22"
