homeassistant:
  #  external_url: "https://hass.khau.lan/"
  #  internal_url: "http://dockerhost01.khamu.lan:8123"
  allowlist_external_dirs:
    - "/tmp"

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
#  themes: !include_dir_merge_named themes
#  themes:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  #  db_url: mysql://hassuser:xxxxxxxx@db.khamu.lan/HassDb?charset=utf8
  purge_keep_days: 15

alarm_control_panel:
  - name: HA Alarm
    platform: manual
    unique_id: 6267_home_alarm
    code: !secret alarmpanelcode

homekit:
  filter:
    include_domains:
      - cover
      - light
      - switch
      - alarm_control_panel
      - climate
  entity_config:
    alarm_control_panel.ha_alarm:
      code: !secret alarmpanelcode

http:
  use_x_forwarded_for: true
  trusted_proxies:
    # IPV4 IPAM Subnet of nginx_default Network
    - ::1
    - 127.0.0.1
    # dockerhost01 vm ip
    - 10.21.0.3
    # docker container network
    - 172.18.0.0/16

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telgram_chatid_aj

notify:
  - platform: telegram
    name: telegram_aj
    chat_id: !secret telgram_chatid_aj
