version: "3.3"

services:
      
  orangehrm:
    image: orangehrm/orangehrm
    container_name: orangehrm
    restart: unless-stopped
    ports:
      - 8081:80
      - 8082:443
    volumes:
      - ./orange:/orangehrm
    environment:
      - PUID=998
      - PGID=100
    depends_on:
      - mariadb
    links:
      - mariadb:mariadb      

  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./db_orange:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=orangehrm
      - MYSQL_USER=orangeuser
      - MYSQL_PASSWORD=orangepassword

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
