version: '3'

services:

  mqtt:
    image: eclipse-mosquitto
    container_name: Mqtt
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - "./mqttconfig:/mosquitto/config:rw"
      - "./mqttdata:/mosquitto/data:rw"
      - "./mqttlog:/mosquitto/log:rw"

#docker exec -it hass_test_1 /bin/sh
