services:

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
#    ports:
#      - 1883:1883
#      - 9001:9001
    restart: unless-stopped
    volumes:
      - "./mqttconfig:/mosquitto/config:rw"
      - "./mqttdata:/mosquitto/data:rw"
      - "./mqttlog:/mosquitto/log:rw"
    labels:
      traefik.enable: true
      traefik.tcp.services.mqtt.loadbalancer.server.port: 1883 # port to redirect to
      traefik.tcp.routers.mqtt.rule: HostSNI(`*`) # url for the application
      traefik.tcp.routers.mqtt.entrypoints: mqtt
    networks:
      - traefik-network

networks:
  traefik-network:
    name: traefik-network
    external: true



#docker compose exec mqtt /bin/sh
