# https://github.com/Cingulara/dotnet-core-prometheus-grafana/tree/master

version : '3'
 
services:
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  tempo:
    image: grafana/tempo
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempodata:/tmp/tempo

  collector:
    image: otel/opentelemetry-collector-contrib
    container_name: collector
    command: [ "--config=/etc/collector.yaml" ]
    ports:
      - 14268:14268  # jaeger ingest
      - 3200:3200   # tempo
      - 9095:9095 # tempo grpc
      - 4317:4317  # otlp grpc
      - 4318:4318  # otlp http
      - 9411:9411   # zipkin
    volumes:
      - ./otel-collector.yaml:/etc/collector.yaml
    depends_on:
      - tempo

  grafana: 
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
#      - GF_AUTH_DISABLE_LOGIN_FORM=true
#      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - 3000:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - collector
      - tempo
#      - prometheus

  