# https://github.com/Cingulara/dotnet-core-prometheus-grafana/tree/master

version : '3'
 
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - promgrafana

  grafana: 
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=P@ssw0rd
    restart: always
    ports:
      - 3000:3000
    networks:
      - promgrafana

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: Y
    volumes:
      - ./seqdata:/data
    ports:
      - 8080:80
      - 8443:443
      - 5341:5341


### put all the networks here
networks:
  promgrafana: