global:
  scrape_interval: 10s # By default, scrape targets every 5 seconds.

scrape_configs:
  - job_name: "dotnetapp"
    static_configs:
      - targets: ["collector:8889"]
      - targets: ["collector:8888"]
