services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 3306:3306
      - 1883:1883
      - 3000:3000
      # -- (Optional) Enable Dashboard, don't do in production
      - 8080:8080
    volumes:
      - ./config:/etc/traefik
      - ./ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    restart: unless-stopped
    networks:
      - traefik-network

networks:
  traefik-network:
    name: traefik-network

