#
# other congis
#

entryPoints:
  web:
    address: :80
    # Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
  mysql:
    address: :3306
  plex:
    address: :32400
  zwave:
    address: :3000
  mqtt:
    address: :1883

#
# other congis
#

tls:
  stores:
    default:
      defaultCertificate:
        certFile: /ssl-certs/Generic+khamu.lan.crt
        keyFile: /ssl-certs/Generic+khamu.lan.key
#
# other congis
#
