version: '3'

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: timescale
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=changeme
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data