version: '3'

services:
  timescale:
    image: timescale/timescaledb:latest-pg15
    container_name: timescale
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      -./data:/var/lib/postgresql/data