services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - 11434:11434
    volumes:
      - ./models:/models

  openweb-ui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openweb-ui
    ports:
      - 9002:3000
    volumes:
      - ./webuidata:/app/backend/data
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434