#Zone          Pin
#1	            1
#2	            2
#3	            5
#4	            6
#5	            7
#6	            9
#OUT or ALARM	  8

substitutions:
  devicename: konnectedmain
  friendly_name: Konnected Main
  
esphome:
  name: ${devicename}
  platform: ESP8266
  board: nodemcuv2

<<: !include includes/common.yaml
<<: !include includes/haapi.yaml

binary_sensor:
  - <<: !include includes/status.yaml
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: ${friendly_name}_zone_1
    device_class: door
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
    name: ${friendly_name}_zone_2
    device_class: door
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: ${friendly_name}_zone_3
    device_class: motion
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: ${friendly_name}_zone_4
    device_class: window
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
    name: ${friendly_name}_zone_5
    device_class: window
  - platform: gpio
    pin:
      number: D9
      mode: INPUT_PULLUP
    name: ${friendly_name}_zone_6
    device_class: window
  
sensor:
  - <<: !include includes/wifi_signal.yaml
  - <<: !include includes/uptime.yaml

text_sensor:
  - <<: !include includes/wifi_info.yaml
  
switch:
  - <<: !include includes/shutdown.yaml
  - <<: !include includes/restart.yaml