ha_latitude: xxxxxxxx
ha_longitude: xxxxxxxx

iotwifissid: xxxxxxxx
iotwifipass: xxxxxxxx

apFallBackPass: xxxxxxxx

espapipass: xxxxxxxx
espotapass: xxxxxxxx
webpass: xxxxxxxx
encryption_key: xxxxxxxx

mqtthost: mqtt.khamu.lan
mqttuser: xxxxxxxx
mqttpass: xxxxxxxx
