version: '3'

services:
  esphome:
    image: esphome/esphome
    container_name: EspHome
    environment:
      ESPHOME_DASHBOARD_USE_PING: "true"
    ports:
      - 6052:6052
      - 6123:6123
    volumes:
      - ./config:/config
    restart: unless-stopped
