services:
  esphome:
    image: esphome/esphome
    container_name: esphome
    environment:
      ESPHOME_DASHBOARD_USE_PING: "true"
      USERNAME: admin
      PASSWORD: changeme
    volumes:
      - ./config:/config
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.services.esphome.loadbalancer.server.port: 6052 # port to redirect to
      traefik.http.routers.esphome.rule: Host(`esphome.khamu.lan`) # url for the application
      traefik.http.routers.esphome.entrypoints: web, websecure
      traefik.http.routers.esphome.tls: true
    networks:
      - traefik-network

networks:
  traefik-network:
    name: traefik-network
    external: true



