
version: '3'
services:
  web:
    image: nginx
    container_name: web
    ports:
      - 9001:80
    labels:
      traefik.enable: true
      traefik.http.routers.web.rule: Host(`db.khamu.lan`) # url for the application
      traefik.http.routers.web.entrypoints: web, websecure
      traefik.http.routers.web.tls: true
    networks:
      - traefik-network

networks:
  traefik-network:
    name: traefik-network
    external: true
